name: Build and Push to ECR (Private)

on:
  push:
    branches:
      - master  # or your default branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin $(echo "${{ secrets.ECR_REPOSITORY }}" | cut -d'/' -f1)

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.ECR_REPOSITORY }}:latest .
        docker tag ${{ secrets.ECR_REPOSITORY }}:latest ${{ secrets.ECR_REPOSITORY }}:v2

    - name: Push image to ECR
      run: |
        docker push ${{ secrets.ECR_REPOSITORY }}:v2
